apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  annotations:
    avp.kubernetes.io/path: "secrets.sops.yaml"
data:
  url:  https://<argocd | jsonPath {.url}>
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: <argocd | jsonPath {.dex.clientid}>
          clientSecret: <argocd | jsonPath {.dex.clientsecret}>
  resource.customizations.ignoreDifferences.all: |
    jsonPointers:
    - /spec/template/spec/hostUsers
    - /spec/jobTemplate/spec/template/spec/hostUsers

