apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  annotations:
    avp.kubernetes.io/path: "secrets.sops.yaml"
data:
  policy.csv: |
    g, <argocd | jsonPath {.dex.user}>, role:admin
  scopes: '[email]'
