apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: .
    repoURL: https://github.com/tieum/argocd.git
    targetRevision: main
  syncPolicy:
    automated: {}
