apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.7/manifests/install.yaml
  - application/argocd.yaml #self-reference
  - application/argocd-apps.yaml #apps are in another repo
  - config/cmp-plugin.yaml #avp
  - test-secret.yaml #test sops install
patches:
  - path: patch/argocd-repo-server.yaml #avp patches
