apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.7/manifests/install.yaml
  - argocd.yaml #self-reference
  - argocd-apps.yaml #apps are in another repo
  - cmp-plugin.yaml #avp

patches:
  - path: argocd-repo-server.yaml #avp patches
