apiVersion: v1
kind: Secret
metadata:
  name: github-private
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "secrets.sops.yaml"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/tieum/argocd-secrets
  sshPrivateKey: <argocd | jsonPath {.github-ssh-deploy-key}>
