---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: <argocd | jsonPath {.ingress.host}>
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    avp.kubernetes.io/path: "secrets.sops.yaml"
spec:
  ingressClassName: nginx
  rules:
  - host: <argocd | jsonPath {.ingress.host}>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: http
  tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - <argocd | jsonPath {.ingress.host}>
    secretName: argocd-ingress-cert 
